### ISSUE TITLE
hydro-box-dex-launcher: more graceful dealing with revert tx

### ISSUE THREAD

**Issue by mingmin-ddex** [HydroProtocol/hydro-scaffold-dex#24]
```
hydro-box-dex-launcher | Response: {"id":1,"jsonrpc":"2.0","result":"0x85a8b783ba3e8fdb301dace060cc5994d8c301404c6d504e01b34a2f9c14c909","error":{"message":"VM Exception while processing transaction: revert SUB_ERROR","code":-32000,"data":{"0x85a8b783ba3e8fdb301dace060cc5994d8c301404c6d504e01b34a2f9c14c909":{"error":"revert","program_counter":1224,"return":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000095355425f4552524f520000000000000000000000000000000000000000000000","reason":"SUB_ERROR"},"stack":"o: VM Exception while processing transaction: revert SUB_ERROR\n    at Function.o.fromResults (/app/ganache-core.docker.cli.js:10:82299)\n    at /app/ganache-core.docker.cli.js:47:151756\n    at /app/ganache-core.docker.cli.js:47:128087\n    at b (/app/ganache-core.docker.cli.js:47:127744)\n    at /app/ganache-core.docker.cli.js:47:127797\n    at t.default (/app/ganache-core.docker.cli.js:52:259867)\n    at /app/ganache-core.docker.cli.js:47:128711\n    at _.n.emit (/app/ganache-core.docker.cli.js:61:1063005)\n    at /app/ganache-core.docker.cli.js:61:1701802\n    at /app/ganache-core.docker.cli.js:61:1701825\n    at /app/ganache-core.docker.cli.js:61:351481\n    at /app/ganache-core.docker.cli.js:2:69007\n    at i (/app/ganache-core.docker.cli.js:2:84062)\n    at /app/ganache-core.docker.cli.js:2:64530\n    at process._tickCallback (internal/process/next_tick.js:61:11)","name":"o"}}}
hydro-box-dex-launcher |
hydro-box-dex-launcher | time="2019-05-06T04:01:28Z" level=info msg="Send Tx failed, launchLog ID: 5, err: Error -32000 (VM Exception while processing transaction: revert SUB_ERROR)"
hydro-box-dex-launcher | time="2019-05-06T04:01:28Z" level=info msg="launcher stop!"
hydro-box-dex-launcher | panic: Error -32000 (VM Exception while processing transaction: revert SUB_ERROR)
hydro-box-dex-launcher |
hydro-box-dex-launcher | goroutine 1 [running]:
hydro-box-dex-launcher | main.Run(0xc000513f38, 0xacc4a0)
hydro-box-dex-launcher | 	/app/cli/launcher/main.go:95 +0x81d
hydro-box-dex-launcher | main.run(0xc000080058)
hydro-box-dex-launcher | 	/app/cli/launcher/main.go:33 +0x26a
hydro-box-dex-launcher | main.main()
hydro-box-dex-launcher | 	/app/cli/launcher/main.go:116 +0x22
...
hydro-box-dex-launcher exited with code 2
```

**Comment by mingmin-ddex** [comment]
caused by `l.BlockChain.SendRawTransaction(signedRawTransaction)` returning err when send a tx which will revert.

won't happen for ropsten & mainnet, only occur at localhost using ganach.

the revert tx is caused by corner cases of small matched order, which is fixed.

so no special work need to be done for this issue now
